spring.datasource.url=jdbc:mysql://localhost:3306/resourceloop
spring.datasource.username=root
spring.datasource.password=Kshitij@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=PHER2TN81CQU826ubaJlaewr1VC33rH668xO4QPCj5G
app.jwt.expiration-ms=86400000
app.cors.allowed-origin=http://localhost:3000
